const questions = [
  { id: 1, text: "Jika 3x + 5 = 20, maka nilai dari 2x - 4 adalah...", choices: ["6", "8", "10", "12"], answer: 0, type: "single" },
  { id: 2, text: "Hasil dari (12² - 8²) ÷ 4 adalah...", choices: ["16", "20", "24", "32"], answer: 2, type: "single" },
  { id: 3, text: "Rata-rata dari 8, 12, 15, 25, dan 30 adalah...", choices: ["16", "17", "18", "20"], answer: 3, type: "single" },
  { id: 4, text: "Bentuk sederhana dari (2x - 3)(x + 4) adalah...", choices: ["2x² + 5x - 12", "2x² - 5x - 12", "2x² + 8x - 3", "2x² + 5x + 12"], answer: 0, type: "single" },
  { id: 5, text: "Jika sin A = 3/5 dan A sudut lancip, maka cos A = ...", choices: ["4/5", "3/4", "5/3", "√2/2"], answer: 0, type: "single" },
  { id: 6, text: "Sebuah toko memberi diskon 20% untuk barang seharga Rp250.000. Harga setelah diskon adalah...", choices: ["Rp 180.000", "Rp 190.000", "Rp 200.000", "Rp 210.000"], answer: 2, type: "single" },
  { id: 7, text: "Jika 4 pekerja menyelesaikan pekerjaan dalam 12 hari, maka 6 pekerja dengan kecepatan sama akan menyelesaikan pekerjaan dalam...", choices: ["6 hari", "7 hari", "8 hari", "9 hari"], answer: 2, type: "single" },
  { id: 8, text: "Diketahui data nilai: 5, 8, 8, 10, 12, 15, 15. Modus dari data tersebut adalah...", choices: ["8", "10", "12", "15"], answer: 3, type: "single" },
  { id: 9, text: "Jika x : y = 4 : 5 dan y : z = 10 : 3, maka x : y : z = ...", choices: ["8 : 10 : 3", "4 : 5 : 6", "12 : 15 : 10", "8 : 10 : 6"], answer: 0, type: "single" },
  { id: 10, text: "Sebuah dadu dilempar. Peluang muncul mata dadu genap adalah...", choices: ["1/6", "1/3", "1/2", "2/3"], answer: 2, type: "single" },
  { id: 11, text: "Bacalah teks berikut: 'Air adalah komponen penting bagi kehidupan. Kekurangan air dapat menyebabkan dehidrasi dan gangguan fungsi organ.' Ide pokok teks tersebut adalah...", choices: ["Air dapat diminum", "Air penting untuk kehidupan", "Air menyebabkan dehidrasi", "Fungsi organ"], answer: 1, type: "single" },
  { id: 12, text: "Jika x² - 7x + 12 = 0, maka x adalah...", choices: ["3 atau 4", "4 atau 5", "3 atau 5", "2 atau 6"], answer: 0, type: "single" },
  { id: 13, text: "Nilai dari log₂ 32 adalah...", choices: ["3", "4", "5", "6"], answer: 2, type: "single" },
  { id: 14, text: "Jika A = {1, 2, 3, 4}, B = {3, 4, 5, 6}, maka A ∩ B = ...", choices: ["{1,2,3,4,5,6}", "{3,4}", "{1,2}", "{5,6}"], answer: 1, type: "single" },
  { id: 15, text: "Sebuah segitiga memiliki panjang sisi 5 cm, 12 cm, dan 13 cm. Jenis segitiga tersebut adalah...", choices: ["Siku-siku", "Sama kaki", "Sama sisi", "Sembarang"], answer: 0, type: "single" },
  { id: 16, text: "Rata-rata 5 bilangan adalah 14. Jika salah satu bilangan yang digunakan adalah 24, maka rata-rata 4 bilangan lainnya adalah...", choices: ["11", "12", "13", "14"], answer: 1, type: "single" },
  { id: 17, text: "Jika 2x + y = 10 dan x - y = 2, maka x = ...", choices: ["3", "4", "5", "6"], answer: 1, type: "single" },
  { id: 18, text: "Pernyataan yang benar tentang bilangan prima adalah...", choices: ["Hanya habis dibagi 1 dan dirinya", "Selalu bilangan ganjil", "Selalu bilangan genap", "Tidak punya faktor"], answer: 0, type: "single" },
  { id: 19, text: "Jumlah sudut segi enam adalah...", choices: ["360°", "540°", "720°", "900°"], answer: 2, type: "single" },
  { id: 20, text: "Volume balok dengan panjang 5 cm, lebar 4 cm, tinggi 3 cm adalah...", choices: ["60 cm³", "65 cm³", "70 cm³", "80 cm³"], answer: 3, type: "single" },
  { id: 21, text: "Jika a² + b² = c², maka segitiga dengan sisi a, b, c adalah segitiga...", choices: ["Siku-siku", "Tumpul", "Lancip", "Sama sisi"], answer: 0, type: "single" },
  { id: 22, text: "Hasil dari (3/4) ÷ (2/5) adalah...", choices: ["15/8", "8/15", "5/6", "6/5"], answer: 0, type: "single" },
  { id: 23, text: "Urutan bilangan berikut yang benar dari terbesar ke terkecil adalah: -2, 0, 3, -5", choices: ["3, 0, -2, -5", "-5, -2, 0, 3", "0, 3, -2, -5", "3, -5, -2, 0"], answer: 0, type: "single" },
  { id: 24, text: "Sebuah kereta menempuh jarak 180 km dalam 3 jam. Kecepatan rata-rata kereta tersebut adalah...", choices: ["40 km/jam", "50 km/jam", "60 km/jam", "70 km/jam"], answer: 2, type: "single" },
  { id: 25, text: "Jika 5! = 120, maka (5!)/(3!) = ...", choices: ["10", "15", "20", "40"], answer: 2, type: "single" },
  { id: 26, text: "Hasil dari 2⁴ × 3² adalah...", choices: ["72", "96", "144", "162"], answer: 0, type: "single" },
  { id: 27, text: "Sebuah kelas terdiri dari 12 laki-laki dan 18 perempuan. Peluang terpilih seorang laki-laki adalah...", choices: ["1/2", "2/3", "2/5", "1/3"], answer: 3, type: "single" },
  { id: 28, text: "Sebuah tabung memiliki jari-jari 7 cm dan tinggi 10 cm. Volume tabung adalah... (π = 22/7)", choices: ["1.540 cm³", "1.5400 cm³", "1.540 cm²", "1.5400 cm²"], answer: 0, type: "single" },
  { id: 29, text: "Jika x + y = 12 dan xy = 20, maka x dan y adalah akar dari persamaan...", choices: ["t² - 12t + 20 = 0", "t² - 20t + 12 = 0", "t² + 12t - 20 = 0", "t² - 8t + 15 = 0"], answer: 0, type: "single" },
  { id: 30, text: "Bentuk sederhana dari √50 adalah...", choices: ["5√2", "10√2", "2√5", "5√5"], answer: 0, type: "single" },
  { id: 31, text: "Jika 40% dari sebuah bilangan adalah 80, maka bilangan tersebut adalah...", choices: ["160", "180", "200", "220"], answer: 2, type: "single" },
  { id: 32, text: "Nilai maksimum dari fungsi y = -x² + 4x + 5 adalah...", choices: ["7", "9", "11", "13"], answer: 2, type: "single" },
  { id: 33, text: "Dalam logika, kontraposisi dari 'Jika hujan maka jalan basah' adalah...", choices: ["Jika tidak hujan maka jalan tidak basah", "Jika jalan tidak basah maka tidak hujan", "Jika hujan maka tidak basah", "Jika basah maka hujan"], answer: 1, type: "single" },
  { id: 34, text: "Jika f(x) = 2x + 3, maka f⁻¹(x) adalah...", choices: ["(x - 3)/2", "2x - 3", "(x + 3)/2", "2x + 3"], answer: 0, type: "single" },
  { id: 35, text: "Jika data 2, 3, 4, 5, 100 diberikan, median dari data tersebut adalah...", choices: ["4", "5", "3", "100"], answer: 0, type: "single" },
  { id: 36, text: "Jika sebuah peluang kejadian adalah 0,25 maka peluang komplemennya adalah...", choices: ["0,50", "0,60", "0,70", "0,75"], answer: 3, type: "single" },
  { id: 37, text: "Jika 3x = 27 maka nilai log₃ x adalah...", choices: ["1", "2", "3", "0"], answer: 1, type: "single" },
  { id: 38, text: "Jika sebuah perusahaan mengalami kenaikan laba 10% dari Rp200 juta, maka laba baru adalah...", choices: ["Rp210 juta", "Rp220 juta", "Rp230 juta", "Rp240 juta"], answer: 0, type: "single" },
  { id: 39, text: "Jika barisan aritmetika memiliki suku pertama 5 dan beda 3, maka suku ke-10 adalah...", choices: ["32", "33", "34", "35"], answer: 1, type: "single" },
  { id: 40, text: "Himpunan penyelesaian dari |x - 3| = 5 adalah...", choices: ["x = 8 atau x = -2", "x = 8 atau x = 2", "x = 5 atau x = -5", "x = -8 atau x = 2"], answer: 0, type: "single" },
  { id: 41, text: "Hasil dari (5/6) + (7/12) adalah...", choices: ["17/12", "19/12", "21/12", "23/12"], answer: 1, type: "single" },
  { id: 42, text: "Jika 2 log x = 6, maka x = ...", choices: ["64", "128", "256", "512"], answer: 2, type: "single" },
  { id: 43, text: "Median dari data 4, 7, 8, 10, 12, 15, 20 adalah...", choices: ["8", "9", "10", "11"], answer: 2, type: "single" },
  { id: 44, text: "Sebuah koin dilempar dua kali. Peluang muncul minimal satu sisi angka adalah...", choices: ["1/4", "1/2", "3/4", "1"], answer: 2, type: "single" },
  { id: 45, text: "Hasil dari (x² - 9) ÷ (x - 3) untuk x ≠ 3 adalah...", choices: ["x - 3", "x + 3", "x² + 3", "x² - 3"], answer: 1, type: "single" },
  { id: 46, text: "Jika x + y = 14 dan x - y = 6, maka nilai x adalah...", choices: ["4", "5", "10", "12"], answer: 2, type: "single" },
  { id: 47, text: "Volume prisma segitiga dengan alas 6 cm, tinggi alas 8 cm, dan tinggi prisma 10 cm adalah...", choices: ["240 cm³", "250 cm³", "260 cm³", "280 cm³"], answer: 0, type: "single" },
  { id: 48, text: "Dalam logika, negasi dari pernyataan 'Semua siswa rajin' adalah...", choices: ["Tidak ada siswa rajin", "Sebagian siswa rajin", "Ada siswa yang tidak rajin", "Semua siswa malas"], answer: 2, type: "single" },
  { id: 49, text: "Jika peluang suatu kejadian adalah 0,4 maka odds kejadian tersebut adalah...", choices: ["2 : 3", "3 : 2", "4 : 6", "6 : 4"], answer: 0, type: "single" },
  { id: 50, text: "Hasil dari 3√(64) adalah...", choices: ["2", "3", "4", "8"], answer: 2, type: "single" },
  { id: 51, text: "Jika f(x) = x² - 4x + 3, maka nilai minimum f(x) adalah...", choices: ["-1", "0", "1", "3"], answer: 2, type: "single" },
  { id: 52, text: "Bentuk sederhana dari 5log 100 adalah...", choices: ["2", "3", "4", "5"], answer: 0, type: "single" },
  { id: 53, text: "Jika 40% dari suatu bilangan adalah 48, maka 75% dari bilangan tersebut adalah...", choices: ["80", "85", "90", "100"], answer: 2, type: "single" },
  { id: 54, text: "Sebuah relasi R didefinisikan pada A = {1,2,3} dengan R = {(1,1),(2,2),(3,3)}. Relasi ini adalah...", choices: ["Refleksif", "Simetris", "Transitif", "Semua benar"], answer: 3, type: "single" },
  { id: 55, text: "Hasil dari 2sin²30° + cos²60° adalah...", choices: ["1/2", "3/4", "1", "3/2"], answer: 2, type: "single" },
  { id: 56, text: "Jika x berbanding lurus dengan y dan x = 12 saat y = 8, maka nilai y saat x = 9 adalah...", choices: ["5", "6", "7", "8"], answer: 1, type: "single" },
  { id: 57, text: "Bentuk faktorisasi dari x² - 16 adalah...", choices: ["(x - 8)(x + 8)", "(x - 4)(x + 4)", "(x - 16)(x + 1)", "(x - 2)(x + 8)"], answer: 1, type: "single" },
  { id: 58, text: "Jumlah suku pertama 10 dari barisan aritmetika dengan a₁ = 5 dan beda 3 adalah...", choices: ["140", "145", "150", "155"], answer: 2, type: "single" },
  { id: 59, text: "Jika harga barang naik 20% kemudian turun 20%, maka persentase perubahan harga adalah...", choices: ["Turun 4%", "Naik 4%", "Turun 2%", "Tidak berubah"], answer: 0, type: "single" },
  { id: 60, text: "Penyelesaian dari pertidaksamaan 2x - 3 > 5 adalah...", choices: ["x > 2", "x > 3", "x > 4", "x > 5"], answer: 2, type: "single" },
  { id: 61, text: "Jika peluang A = 0,3 dan peluang B = 0,5 (saling lepas), maka P(A ∪ B) = ...", choices: ["0,15", "0,5", "0,8", "0,9"], answer: 2, type: "single" },
  { id: 62, text: "Jika det(M) = 10, maka det(2M) = ...", choices: ["10", "20", "40", "100"], answer: 2, type: "single" },
  { id: 63, text: "Jika vektor a = (3,4), maka panjang vektor a adalah...", choices: ["3", "4", "5", "6"], answer: 2, type: "single" },
  { id: 64, text: "Gradien garis melalui titik (2,3) dan (6,11) adalah...", choices: ["1", "2", "3", "4"], answer: 1, type: "single" },
  { id: 65, text: "Jika matriks A = [[1,2],[3,4]], maka tr(A) adalah...", choices: ["3", "4", "5", "6"], answer: 2, type: "single" },
  { id: 66, text: "Limit dari (x² - 9)/(x - 3) saat x → 3 adalah...", choices: ["0", "3", "6", "9"], answer: 2, type: "single" },
  { id: 67, text: "Jika sebuah peluang adalah 3 : 2, maka probabilitas kejadian tersebut adalah...", choices: ["0,3", "0,4", "0,6", "0,75"], answer: 2, type: "single" },
  { id: 68, text: "Sebuah barisan geometri memiliki a₁ = 3 dan r = 2. Suku ke-6 adalah...", choices: ["48", "60", "96", "192"], answer: 2, type: "single" },
  { id: 69, text: "Turunan dari y = x³ - 3x² + 5x adalah...", choices: ["3x² - 6x + 5", "3x² + 6x + 5", "x² - 3x + 5", "3x - 3"], answer: 0, type: "single" },
  { id: 70, text: "Integral ∫ 2x dx adalah...", choices: ["x² + C", "2x² + C", "x + C", "x²"], answer: 0, type: "single" },
  { id: 71, text: "Jika peluang sukses 0,7 maka peluang gagal adalah...", choices: ["0,2", "0,3", "0,4", "0,5"], answer: 1, type: "single" },
  { id: 72, text: "Bentuk sederhana dari ⁴√81 adalah...", choices: ["2", "3", "4", "9"], answer: 1, type: "single" },
  { id: 73, text: "Hasil dari 6P2 adalah...", choices: ["15", "20", "30", "36"], answer: 2, type: "single" },
  { id: 74, text: "Jumlah semua sudut pada segi delapan adalah...", choices: ["720°", "900°", "1080°", "1260°"], answer: 2, type: "single" },
  { id: 75, text: "Jika f(x) = 3x + 1, maka f(2) = ...", choices: ["5", "6", "7", "8"], answer: 0, type: "single" },
  { id: 76, text: "Hasil dari (tan 45° + sin 30°) adalah...", choices: ["1", "1,5", "1,7", "2"], answer: 1, type: "single" },
  { id: 77, text: "Jika nilai ekspektasi dari sebuah pelemparan dadu adalah...", choices: ["3", "3,5", "4", "4,5"], answer: 1, type: "single" },
  { id: 78, text: "Jika x → ∞, maka limit dari 1/x adalah...", choices: ["0", "1", "∞", "Tidak ada"], answer: 0, type: "single" },
  { id: 79, text: "Jika barisan aritmetika memiliki a₁ = 10 dan a₅ = 26, maka beda barisan adalah...", choices: ["3", "4", "5", "6"], answer: 2, type: "single" },
  { id: 80, text: "Jika 3^(x+1) = 81, maka x = ...", choices: ["2", "3", "4", "5"], answer: 1, type: "single" },
  { id: 81, text: "Premis 1: Semua burung dapat terbang. Premis 2: Penguin adalah burung. Kesimpulan yang benar adalah...", choices: ["Penguin dapat terbang", "Penguin tidak dapat terbang", "Sebagian penguin dapat terbang", "Kesimpulan tidak valid"], answer: 3, type: "single" },
  { id: 82, text: "Anton lebih tinggi dari Budi. Budi lebih tinggi dari Caca. Siapa yang paling pendek?", choices: ["Anton", "Budi", "Caca", "Tidak diketahui"], answer: 2, type: "single" },
  { id: 83, text: "Pernyataan: 'Jika hujan maka jalanan basah.' Kontraposisi dari pernyataan tersebut adalah...", choices: ["Jika tidak hujan maka jalanan tidak basah", "Jika jalanan tidak basah maka tidak hujan", "Jika jalanan basah maka hujan", "Jalanan basah jika hujan"], answer: 1, type: "single" },
  { id: 84, text: "Jumlah kata dalam kalimat 'Mereka belajar bersama di perpustakaan' adalah...", choices: ["4", "5", "6", "7"], answer: 1, type: "single" },
  { id: 85, text: "Pilih antonim kata 'rigid' dalam bahasa Inggris...", choices: ["Flexible", "Stiff", "Solid", "Hard"], answer: 0, type: "single" },
  { id: 86, text: "Ide pokok dari paragraf yang menjelaskan pentingnya menjaga kebersihan lingkungan adalah...", choices: ["Lingkungan harus dijaga", "Kebersihan penting", "Sampah menyebabkan banjir", "Hidup sehat menyenangkan"], answer: 1, type: "single" },
  { id: 87, text: "Peribahasa 'bagai air di daun talas' bermakna...", choices: ["Orang yang tidak tetap pendiriannya", "Orang yang sabar", "Orang yang tekun", "Orang yang mudah marah"], answer: 0, type: "single" },
  { id: 88, text: "Kalimat efektif dari 'Dia pergi ke pasar untuk membeli sayur dan buah-buahan ke pasar' adalah...", choices: ["Dia pergi ke pasar untuk membeli sayur dan buah-buahan", "Dia pergi ke pasar membeli sayur", "Dia ke pasar membeli buah", "Dia membeli sayur dan buah-buahan"], answer: 0, type: "single" },
  { id: 89, text: "Sinonim kata 'kompleks' adalah...", choices: ["Rumit", "Sederhana", "Biasa", "Mudah"], answer: 0, type: "single" },
  { id: 90, text: "Jika 'semua guru adalah pegawai', maka pernyataan yang pasti benar adalah...", choices: ["Semua pegawai adalah guru", "Sebagian pegawai adalah guru", "Tidak ada pegawai yang guru", "Guru bukan pegawai"], answer: 1, type: "single" },
  { id: 91, text: "Rata-rata dari 12, 15, 20, 25 adalah...", choices: ["18", "19", "20", "21"], answer: 1, type: "single" },
  { id: 92, text: "Teks: 'Indonesia adalah negara kepulauan yang memiliki ribuan pulau.' Ide pokok dari kalimat tersebut adalah...", choices: ["Indonesia negara kepulauan", "Indonesia punya ribuan pulau", "Negara kepulauan memiliki banyak pulau", "Indonesia luas"], answer: 0, type: "single" },
  { id: 93, text: "Urutkan kata berikut agar menjadi kalimat efektif: 'Makan – Siswa – Bersama – Kantin – Di'", choices: ["Siswa makan bersama di kantin", "Makan siswa bersama di kantin", "Siswa di kantin makan bersama", "Di kantin siswa makan bersama"], answer: 0, type: "single" },
  { id: 94, text: "Jika sebuah teks berisi 120 kata dan dapat dibaca dalam 1 menit, maka kecepatan membaca adalah...", choices: ["100 kata/menit", "110 kata/menit", "120 kata/menit", "130 kata/menit"], answer: 2, type: "single" },
  { id: 95, text: "Tentukan ide pokok dari teks yang menjelaskan bahaya merokok bagi kesehatan paru-paru...", choices: ["Rokok menyebabkan kanker paru", "Rokok berbahaya", "Kesehatan paru penting", "Merokok dilarang"], answer: 1, type: "single" },
  { id: 96, text: "Makna kata 'kontradiktif' adalah...", choices: ["Sejalan", "Bertentangan", "Sama", "Serupa"], answer: 1, type: "single" },
  { id: 97, text: "Dari premis: 'Sebagian siswa rajin.' Maka pernyataan yang salah adalah...", choices: ["Semua siswa rajin", "Sebagian siswa tidak rajin", "Ada siswa yang rajin", "Tidak semua siswa malas"], answer: 0, type: "single" },
  { id: 98, text: "Teks menyatakan: 'Ikan adalah hewan berdarah dingin.' Kesimpulan yang tepat adalah...", choices: ["Semua hewan berdarah dingin adalah ikan", "Ikan termasuk hewan berdarah dingin", "Ikan bukan hewan berdarah dingin", "Sebagian ikan berdarah panas"], answer: 1, type: "single" },
  { id: 99, text: "Kalimat yang memiliki makna konotatif adalah...", choices: ["Dia makan nasi di rumah", "Dia bintang di kelas", "Dia membeli buku", "Dia membaca koran"], answer: 1, type: "single" },
  { id: 100, text: "Pilih kalimat yang menggunakan EYD dengan benar...", choices: ["Saya pergi kepasar pagi-pagi", "Saya pergi ke pasar pagi-pagi", "Saya pergi kepasar pagi pagi", "Saya pergi ke pasar, pagi pagi"], answer: 1, type: "single" },
  { id: 101, text: "Jika x² = 121, maka nilai x yang mungkin adalah...", choices: ["11", "-11", "11 dan -11", "0"], answer: 2, type: "single" },
  { id: 102, text: "Jika data: 2, 4, 4, 6, 8 maka modusnya adalah...", choices: ["2", "4", "6", "Tidak ada"], answer: 1, type: "single" },
  { id: 103, text: "Urutkan pecahan 1/2, 3/4, 2/3 dari yang terbesar...", choices: ["1/2, 2/3, 3/4", "3/4, 2/3, 1/2", "2/3, 3/4, 1/2", "3/4, 1/2, 2/3"], answer: 1, type: "single" },
  { id: 104, text: "Jika 5x = 45, maka x = ...", choices: ["7", "8", "9", "10"], answer: 2, type: "single" },
  { id: 105, text: "Bentuk sederhana dari (2x + 3)(x - 4) adalah...", choices: ["2x² + 3x - 12", "2x² - 5x - 12", "2x² - 8x + 3x - 12", "2x² - 5x + 12"], answer: 1, type: "single" },
  { id: 106, text: "Jika peluang hujan 0,3 maka peluang tidak hujan adalah...", choices: ["0,7", "0,6", "0,5", "0,4"], answer: 0, type: "single" },
  { id: 107, text: "Deret: 2, 4, 8, 16, ... suku ke-6 adalah...", choices: ["32", "48", "64", "128"], answer: 2, type: "single" },
  { id: 108, text: "Jika luas lingkaran πr² = 154 (π=22/7), maka jari-jari r adalah...", choices: ["6", "7", "8", "9"], answer: 1, type: "single" },
  { id: 109, text: "Jumlah semua bilangan ganjil dari 1 sampai 9 adalah...", choices: ["20", "21", "25", "30"], answer: 1, type: "single" },
  { id: 110, text: "Hasil dari | -15 | adalah...", choices: ["-15", "0", "15", "Tidak terdefinisi"], answer: 2, type: "single" },
  { id: 111, text: "Hasil dari 0,25 × 0,4 adalah...", choices: ["0,1", "0,05", "0,08", "0,12"], answer: 2, type: "single" },
  { id: 112, text: "Hasil akhir dari 2³ × 3² adalah...", choices: ["36", "72", "64", "54"], answer: 1, type: "single" },
  { id: 113, text: "Bilangan prima antara 30 dan 40 adalah...", choices: ["31, 33, 37", "31, 37", "33, 35, 37", "37, 39"], answer: 1, type: "single" },
  { id: 114, text: "Faktor persekutuan terbesar dari 24 dan 36 adalah...", choices: ["6", "8", "12", "18"], answer: 2, type: "single" },
  { id: 115, text: "Jika x + 3 = 0 maka x = ...", choices: ["-3", "0", "3", "1"], answer: 0, type: "single" },
  { id: 116, text: "Persamaan garis yang melalui titik (0,3) dengan gradien 2 adalah...", choices: ["y = 2x + 3", "y = 3x + 2", "y = 2x - 3", "y = x + 3"], answer: 0, type: "single" },
  { id: 117, text: "Turunan dari y = 5x adalah...", choices: ["5x", "5", "x", "0"], answer: 1, type: "single" },
  { id: 118, text: "Integral ∫ x dx adalah...", choices: ["x²", "x²/2 + C", "x + C", "x² + C"], answer: 1, type: "single" },
  { id: 119, text: "Sebuah segitiga memiliki sudut 40° dan 60°, sudut ketiganya adalah...", choices: ["70°", "80°", "90°", "100°"], answer: 1, type: "single" },
  { id: 120, text: "Jika 10% dari x = 25, maka x = ...", choices: ["200", "250", "300", "350"], answer: 1, type: "single" },
  { id: 121, text: "Jika 3x - 7 = 11 maka nilai x adalah...", choices: ["4", "5", "6", "7"], answer: 3, type: "single" },
  { id: 122, text: "Hasil dari 5³ + 2³ adalah...", choices: ["125", "133", "117", "150"], answer: 1, type: "single" },
  { id: 123, text: "Nilai x pada 2x + 3x = 40 adalah...", choices: ["8", "10", "12", "15"], answer: 1, type: "single" },
  { id: 124, text: "Sebuah kotak berisi 6 bola merah, 4 bola biru. Peluang terambil bola biru adalah...", choices: ["0,4", "0,5", "0,6", "0,3"], answer: 0, type: "single" },
  { id: 125, text: "Jika A = {1,2,3}, B = {3,4,5}, maka A ∩ B = ...", choices: ["{1,2,3,4,5}", "{1,2}", "{3}", "{4,5}"], answer: 2, type: "single" },
  { id: 126, text: "Median dari 3, 5, 7, 9, 11 adalah...", choices: ["5", "7", "9", "8"], answer: 1, type: "single" },
  { id: 127, text: "Jumlah sudut dalam segi delapan adalah...", choices: ["900°", "1080°", "1260°", "1440°"], answer: 1, type: "single" },
  { id: 128, text: "Bilangan 45 habis dibagi oleh...", choices: ["2,3,5", "3,5,9", "3,5,15", "5,9"], answer: 2, type: "single" },
  { id: 129, text: "Jika 4x - 8 = 0, maka nilai x adalah...", choices: ["0", "1", "2", "4"], answer: 2, type: "single" },
  { id: 130, text: "Faktor prima dari 84 adalah...", choices: ["2,3,7", "2,3,5,7", "2,3,11", "3,7,11"], answer: 0, type: "single" },
  { id: 131, text: "Jika sebuah persegi panjang memiliki panjang 12 dan lebar 8, kelilingnya adalah...", choices: ["20", "36", "40", "48"], answer: 2, type: "single" },
  { id: 132, text: "Hasil dari √144 adalah...", choices: ["10", "11", "12", "14"], answer: 2, type: "single" },
  { id: 133, text: "Sebuah kereta menempuh jarak 180 km dalam 3 jam. Kecepatan rata-rata kereta adalah...", choices: ["50 km/jam", "55 km/jam", "60 km/jam", "65 km/jam"], answer: 2, type: "single" },
  { id: 134, text: "Jika x² - 16 = 0 maka x adalah...", choices: ["±3", "±4", "±5", "±6"], answer: 1, type: "single" },
  { id: 135, text: "Peluang mendapatkan angka genap dari pelemparan satu dadu adalah...", choices: ["1/3", "1/2", "2/3", "3/6"], answer: 1, type: "single" },
  { id: 136, text: "Nilai dari 2(3+4) - 5 adalah...", choices: ["7", "9", "10", "12"], answer: 1, type: "single" },
  { id: 137, text: "Jika sebuah lingkaran memiliki diameter 14 cm, kelilingnya adalah... (π=22/7)", choices: ["44 cm", "48 cm", "52 cm", "56 cm"], answer: 0, type: "single" },
  { id: 138, text: "Hasil dari 0,6 × 0,5 adalah...", choices: ["0,2", "0,3", "0,25", "0,35"], answer: 1, type: "single" },
  { id: 139, text: "Persamaan garis yang tegak lurus dengan y = 2x + 3 memiliki gradien...", choices: ["-1/2", "-2", "1/2", "2"], answer: 0, type: "single" },
  { id: 140, text: "Jumlah dari 2, 4, 6, ... , 20 adalah...", choices: ["100", "110", "120", "130"], answer: 2, type: "single" },
  { id: 141, text: "Turunan dari y = x² + 3x adalah...", choices: ["x² + 3", "2x + 3", "x + 3", "2x"], answer: 1, type: "single" },
  { id: 142, text: "Nilai x jika log₁₀ x = 2 adalah...", choices: ["10", "20", "100", "1000"], answer: 2, type: "single" },
  { id: 143, text: "Nilai determinan matriks [[2,3],[4,5]] adalah...", choices: ["-2", "-3", "-5", "-7"], answer: 3, type: "single" },
  { id: 144, text: "Jika 2/5 dari sebuah bilangan adalah 12, maka bilangan itu adalah...", choices: ["20", "25", "30", "40"], answer: 2, type: "single" },
  { id: 145, text: "Bentuk sederhana dari 5x/10 adalah...", choices: ["x/2", "x", "2x", "5x"], answer: 0, type: "single" },
  { id: 146, text: "Jika sebuah balok memiliki p=5, l=4, t=3 maka volumenya adalah...", choices: ["60", "50", "45", "40"], answer: 0, type: "single" },
  { id: 147, text: "Jika x = 2 maka nilai dari x³ + 2x adalah...", choices: ["10", "12", "14", "16"], answer: 2, type: "single" },
  { id: 148, text: "Hasil dari 8! / 7! adalah...", choices: ["7", "8", "9", "56"], answer: 1, type: "single" },
  { id: 149, text: "Bilangan Fibonacci ke-7 (dengan F1=1, F2=1) adalah...", choices: ["8", "9", "10", "13"], answer: 0, type: "single" },
  { id: 150, text: "Sebuah tabung memiliki jari-jari 7 dan tinggi 10. Volume tabung adalah... (π=22/7)", choices: ["1540", "1400", "1320", "1200"], answer: 0, type: "single" },
  { id: 151, text: "Hasil dari sin²30° + cos²30° adalah...", choices: ["0", "1", "0,5", "2"], answer: 1, type: "single" },
  { id: 152, text: "Hasil dari 3⁰ + 4⁰ adalah...", choices: ["0", "1", "2", "3"], answer: 2, type: "single" },
  { id: 153, text: "Bilangan yang habis dibagi 3 dan 4 sekaligus adalah kelipatan...", choices: ["6", "8", "12", "24"], answer: 2, type: "single" },
  { id: 154, text: "Nilai dari (2x²) jika x = 3 adalah...", choices: ["9", "12", "18", "20"], answer: 2, type: "single" },
  { id: 155, text: "Jika sebuah prisma alasnya segitiga dengan luas 20 cm² dan tingginya 6 cm, volumenya adalah...", choices: ["100", "110", "120", "130"], answer: 2, type: "single" },
  { id: 156, text: "Persamaan kuadrat x² - 5x + 6 = 0 memiliki akar...", choices: ["x=2 dan x=3", "x=3 dan x=4", "x=1 dan x=6", "x=2 dan x=4"], answer: 0, type: "single" },
  { id: 157, text: "Hasil dari (3/4) ÷ (1/2) adalah...", choices: ["3/8", "3/4", "3/2", "2/3"], answer: 2, type: "single" },
  { id: 158, text: "Nilai x yang memenuhi 2x + 5 = 3x - 2 adalah...", choices: ["-7", "7", "-5", "5"], answer: 1, type: "single" },
  { id: 159, text: "Jika sebuah data memiliki mean = 20 dan jumlah data = 10 maka jumlah semua data adalah...", choices: ["100", "150", "200", "250"], answer: 2, type: "single" },
  { id: 160, text: "Peluang muncul angka 5 pada pelemparan sebuah dadu adalah...", choices: ["1/6", "1/5", "1/4", "1/3"], answer: 0, type: "single" }
];

const allQuestions = questions.concat(moreQuestions);